const ON_PAGE_SIZE_CHANGE = 'ON_PAGE_SIZE_CHANGE';
const ON_PAGE_CHANGE = 'ON_PAGE_CHANGE';
const ON_NATION_CHANGE = 'ON_NATION_CHANGE';
const ON_CATEGORY_CHANGE = 'ON_CATEGORY_CHANGE';
const DO_SEARCH = 'HAS_ERROR';
const MESSAGE_NOT_CONNECTED = '未连接以太坊账户!';
const MESSAGE_NO_METAMASK = '未安装MetaMask扩展程序!';
const MESSAGE_NO_NETWORK = '不能解析网络ID!';
const MESSAGE_NO_COINBASE = '不能解析COINBASE!';
const MESSAGE_NO_BALANCE = '无法获取账户金额!';
const MESSAGE_INVALID_CONTRACT_ADDRESS = '错误的合约地址!';

export {
    ON_PAGE_SIZE_CHANGE,
    ON_PAGE_CHANGE,
    ON_NATION_CHANGE,
    ON_CATEGORY_CHANGE,
    DO_SEARCH,
    MESSAGE_NOT_CONNECTED,
    MESSAGE_NO_METAMASK,
    MESSAGE_NO_NETWORK,
    MESSAGE_NO_COINBASE,
    MESSAGE_NO_BALANCE,
    MESSAGE_INVALID_CONTRACT_ADDRESS,
};
